In [125]:
import numpy as np
import pandas as pd
test=np.matrix([[6,14,72],[1,2,6],[0,9,15]])

In [5]:
u, s, vt=np.linalg.svd(test,full_matrices=True)

In [7]:
inv=np.linalg.pinv(test)

In [8]:
inv

matrix([[-0.08163265,  1.48979592, -0.20408163],
        [-0.05102041,  0.30612245,  0.12244898],
        [ 0.03061224, -0.18367347, -0.00680272]])

In [9]:
sol=np.matrix([[92],[9],[24]])

In [10]:
inv.sol

AttributeError: 'matrix' object has no attribute 'sol'

In [135]:
diabetes["Glucose"]
diabetes.to_numpy()

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [127]:
diabetes = pd.read_csv('downloads/diabetes.csv')

In [102]:

x=[[6,148,72,35,0,33.6,0.627,50,1],
[1,85,66,29,0,26.6,0.351,31,0],
[8,183,64,0,0,23.3,0.672,32,1],
[1,89,66,23,94,28.1,0.167,21,0],
[0,137,40,35,168,43.1,2.288,33,1],
[5,116,74,0,0,25.6,0.201,30,0],
[3,78,50,32,88,31,0.248,26,1],
[10,115,0,0,0,35.3,0.134,29,0],
[2,197,70,45,543,30.5,0.158,53,1],
[8,125,96,0,0,0,0.232,54,1],
[4,110,92,0,0,37.6,0.191,30,0],
[10,168,74,0,0,38,0.537,34,1]]

In [103]:
len(x)
glucose=[]

In [104]:
for i in range(12):
    glucose.append([x[i][1]])
    del x[i][8]
    del x[i][3]
    del x[i][1]
    del x[i][0]


In [122]:
x
glucose

[[148],
 [85],
 [183],
 [89],
 [137],
 [116],
 [78],
 [115],
 [197],
 [125],
 [110],
 [168]]

In [106]:
a=np.matrix(x)
inv=np.linalg.pinv(a)
sol=np.matrix(glucose)

In [107]:
weights=np.matmul(inv,sol)
weights

matrix([[0.1195981 ],
        [0.03643379],
        [1.15761632],
        [6.29091176],
        [2.31335447]])

In [108]:
predicted=np.matmul(a,weights)
plist=predicted.tolist()

In [109]:
slist=sol.tolist()

In [110]:
error=(sol-predicted)
error=error.tolist()

In [113]:
std=[]

In [115]:
import math
for i in range(len(error)):
    val=100*math.sqrt((error[i][0]**2)/plist[i][0]**2)
    std.append(val)

In [117]:
std

[11.440401925711758,
 24.51702016245629,
 62.11680378635725,
 4.790732453751347,
 9.590272476649057,
 6.275432109028278,
 26.952302423028225,
 5.704244333433223,
 5.311291346141807,
 9.32965241649106,
 12.092546663652671,
 24.562593622723934]

In [92]:
from scipy import ttest_ind
ttest_ind(slist['h'],plist['i'])

ImportError: cannot import name 'ttest_ind' from 'scipy' (/opt/anaconda3/lib/python3.8/site-packages/scipy/__init__.py)

In [120]:
100-sum(std)/len(std)

83.10972552338126

In [123]:
np.matmul(a,weights)

matrix([[167.11909631],
        [112.60816701],
        [112.8815741 ],
        [ 93.47829502],
        [151.53236687],
        [109.15034425],
        [106.77954622],
        [108.79411771],
        [187.06446145],
        [137.86205009],
        [125.13159672],
        [134.87195081]])